version: '3.8'

services:
    db:
        image: postgres:16
        container_name: pgsql-db
        restart: always
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - ./database/pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
