import CommandSearch from '@/components/client/CommandSearch';
import NavMenu from '@/components/client/NavMenu';
import { IProductCategories } from '@/types/client/IProductCategories';
import { Link, usePage } from '@inertiajs/react';
import { ShoppingCart, User } from 'lucide-react';

interface LayoutProps {
    productCategories: IProductCategories[];
}

export function AppLayout({ children }: React.PropsWithChildren) {
    const { productCategories } = usePage().props as unknown as LayoutProps;

    return (
        <div>
            {/* Header */}
            <div className="relative">
                <div className="flex items-center justify-between border-b-1 border-input">
                    {/* logo */}
                    <div>
                        <Link href="/" className="m-1">
                            <img src="/logo.png" className="h-30 w-45" />
                        </Link>
                    </div>

                    {/* search */}
                    <div className="m-1">
                        <CommandSearch />
                    </div>

                    {/* card and user buttons */}
                    <div className="m-1 flex justify-between">
                        <div className="flex cursor-pointer flex-col items-center p-3 hover:underline">
                            <ShoppingCart className="h-8 w-8" />
                            <h5>Shopping card</h5>
                        </div>

                        <div className="flex cursor-pointer flex-col items-center p-3 hover:underline">
                            <User className="h-8 w-8" />
                            <h5>Log in</h5>
                        </div>
                    </div>
                </div>
                {/* nav with dropdowns */}
                <div className="flex justify-center">
                    <NavMenu productCategories={productCategories} />
                </div>
            </div>

            {/* main */}
            <div className="bg-white">{children}</div>

            {/* Footer */}
            <div className="flex justify-center">
                <h3 className="p-5">All images is generated by chatGPT.</h3>
            </div>
        </div>
    );
}
